apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-component
  description: A sample component
  annotations:
    github.com/project-slug: nehal76/learn-jenkins-app
    jenkins.io/job-full-name: git%20-%20docker%20-test
spec:
  type: service
  lifecycle: production
  owner: nehal76
